Fixes error in python 3.9
```
Traceback (most recent call last):
  File "/usr/local/bin/cronic", line 141, in <module>
    main()
  File "/usr/local/bin/cronic", line 107, in main
    stderr.write(traceback.format_exc())
TypeError: a bytes-like object is required, not 'str'
```